In [26]:
import spacy
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, TfidfTransformer

In [27]:
with open('stopwords.txt', 'r') as f:
    stopwords = f.read().splitlines()
print(stopwords)

['\ufeff.', ',', ';', ':', '/', '?', '!', 'à', 'puis', 'au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'je', 'la', 'le', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'suis', 'es', 'est', 'sommes', 'êtes', 'être', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'avoir', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent', 'ceci', 'cela', 'celà', 'cet', 'cette', 'ici', 'ils', 'les', 'leurs', 'quel', 'quels', 'quelle', 'quelles', 'sans', 'soi', 'tout', 'toute', 'tous', 'toutes', 'sous', 'sur', 'alors', 'ni', 'si', 'car', 'plus', 'moins', '^', 'donc', '"', 'parce', 'puisque', 'chez', 'avant', 'après', 'le', 'son', 'se', 'ce', 'que', 'être', 'un', 'de', 'il', 'elle', 'on', 'ils', 'elles', 'de', 'un', 'une', 'du', 'au', 'et', 'par', 'donc', 'project', 'gutenberg', 'or', 'tm', 'foundation', 'for', 'if', 'not', 'crab', 'copyright', 'max', 'full', 'literary', 'are', 'do', 'archive', 'donation', 'you', 'united', 'states', 'victoria', 'license', 'quelque', 'dont', 'très', 'où', 'ça', 'comme']

In [28]:
vectorizer = CountVectorizer(input='filename', stop_words=stopwords)
dfTransformer = TfidfTransformer()
subLinearTransformer = TfidfTransformer(sublinear_tf=True)
limitedVectorizer = TfidfVectorizer(input='filename', stop_words=stopwords, max_features=1000)

In [29]:
filenames = ['chaps-first_sub_glob.txt','chaps-All-but-first_sub_glob.txt']

In [30]:
colLabels = [fn[6:-4] for fn in filenames]
colLabels

['first_sub_glob', 'All-but-first_sub_glob']

In [31]:
docTermMatrix = vectorizer.fit_transform(filenames)

In [32]:
tfidfMatrix = dfTransformer.fit_transform(docTermMatrix)

In [33]:
subTfidfMatrix = subLinearTransformer.fit_transform(docTermMatrix)

In [34]:
limTfidfMatrix = limitedVectorizer.fit_transform(filenames)

In [35]:
rowLabels = vectorizer.get_feature_names()

In [36]:
df = pd.DataFrame(docTermMatrix.todense().T, columns=colLabels, index=rowLabels)

In [37]:
dfTfidf = pd.DataFrame(tfidfMatrix.todense().T, columns=colLabels, index=rowLabels)

In [38]:
dfSubTfidf = pd.DataFrame(subTfidfMatrix.todense().T, columns=colLabels, index=rowLabels)

In [39]:
def addDistinctivenessScores(df): 
    df['firstDistinct'] = df['first_sub_glob'] - df['All-but-first_sub_glob']
    df['lastDistinct'] = df['All-but-first_sub_glob'] - df['first_sub_glob']

In [40]:
for dfI in [df, dfTfidf, dfSubTfidf]: 
    addDistinctivenessScores(dfI)

# Raw Counts

In [41]:
df.sort_values('firstDistinct', ascending=False).head(15)

,first_sub_glob,All-but-first_sub_glob,firstDistinct,lastDistinct
orque,32,8,24,-24
miton,18,4,14,-14
troll,24,11,13,-13
bernache,20,8,12,-12
martelet,12,1,11,-11
turgotine,12,2,10,-10
grappa,17,10,7,-7
scopolamine,7,1,6,-6
doryphore,23,19,4,-4
plectre,7,3,4,-4
contrevérité,6,2,4,-4
dératisation,12,8,4,-4
puncheur,3,0,3,-3
émilien,7,4,3,-3
pachon,3,0,3,-3

In [42]:
df.sort_values('lastDistinct', ascending=False).head(15)

          first_sub_glob  All-but-first_sub_glob  firstDistinct  lastDistinct
monsieur           16663                  345265        -328602        328602
homme              17677                  271319        -253642        253642
jour               11861                  192896        -181035        181035
main               11669                  192016        -180347        180347
peu                13115                  191129        -178014        178014
femme              13028                  190986        -177958        177958
oeil               12394                  184050        -171656        171656
heure              11212                  179952        -168740        168740
temps              10315                  153584        -143269        143269
fois                8843                  143654        -134811        134811
chose               8775                  142285        -133510        133510
fille               8391                  134327        -125936        125936
madame              6290                  130441        -124151        124151
tête                8557                  131698        -123141        123141
porte               8382                  131315        -122933        122933

# Using TFIDF

In [19]:
dfTfidf.sort_values('firstDistinct', ascending=False).head(n=20)

,lastChaps_adj_rest,All_but_last_adj_rest,firstDistinct,lastDistinct
dernier,0.172100,0.129992,0.042108,-0.042108
blanc,0.134565,0.106178,0.028387,-0.028387
seul,0.245858,0.227467,0.018391,-0.018391
long,0.161027,0.142906,0.018121,-0.018121
vide,0.056772,0.040320,0.016453,-0.016453
humain,0.048702,0.034506,0.014196,-0.014196
noir,0.136723,0.122551,0.014172,-0.014172
autre,0.323181,0.310731,0.012450,-0.012450
nu,0.045606,0.034267,0.011339,-0.011339
vivant,0.041477,0.031078,0.010399,-0.010399
heureux,0.075540,0.065172,0.010369,-0.010369
rouge,0.075071,0.065924,0.009147,-0.009147
bleu,0.060995,0.051911,0.009084,-0.009084
vieux,0.176135,0.167265,0.008870,-0.008870
vert,0.042978,0.034877,0.008101,-0.008101
debout,0.044386,0.036342,0.008044,-0.008044
immobile,0.033125,0.025310,0.007815,-0.007815
lointain,0.026087,0.018555,0.007532,-0.007532
froid,0.056491,0.048982,0.007509,-0.007509
rose,0.040632,0.033545,0.007088,-0.007088

In [20]:
dfTfidf.sort_values('lastDistinct', ascending=False).head(n=20)

,lastChaps_adj_rest,All_but_last_adj_rest,firstDistinct,lastDistinct
jeune,0.196780,0.251597,-0.054817,0.054817
bon,0.235723,0.280859,-0.045136,0.045136
joli,0.032562,0.044968,-0.012406,0.012406
cher,0.073945,0.086178,-0.012233,0.012233
large,0.033500,0.044114,-0.010614,0.010614
certain,0.044855,0.053127,-0.008272,0.008272
pauvre,0.108008,0.116157,-0.008149,0.008149
royal,0.007695,0.015193,-0.007498,0.007498
petit,0.419178,0.426237,-0.007059,0.007059
mauvais,0.053863,0.060706,-0.006842,0.006842
riche,0.026744,0.033351,-0.006607,0.006607
prisonnier,0.009572,0.015544,-0.005972,0.005972
sérieux,0.019894,0.025696,-0.005802,0.005802
naturel,0.021583,0.027283,-0.005700,0.005700
brave,0.022709,0.028362,-0.005653,0.005653
honnête,0.014639,0.020096,-0.005457,0.005457
excellent,0.011261,0.016617,-0.005356,0.005356
sûr,0.067752,0.072969,-0.005217,0.005217
charmant,0.020269,0.025432,-0.005163,0.005163
simple,0.038568,0.043351,-0.004783,0.004783

# TFIDF Limited to Top 1000 MFW

In [21]:
rowLabels_limited = limitedVectorizer.get_feature_names()

In [22]:
dfLimTfidf = pd.DataFrame(limTfidfMatrix.todense().T, columns=colLabels, index=rowLabels_limited)

In [23]:
addDistinctivenessScores(dfLimTfidf)

In [24]:
dfLimTfidf.sort_values('firstDistinct', ascending=False).head(n=20)

,lastChaps_adj_rest,All_but_last_adj_rest,firstDistinct,lastDistinct
dernier,0.172279,0.130090,0.042190,-0.042190
blanc,0.134705,0.106257,0.028447,-0.028447
seul,0.246114,0.227638,0.018476,-0.018476
long,0.161195,0.143014,0.018181,-0.018181
vide,0.056832,0.040350,0.016482,-0.016482
noir,0.136865,0.122643,0.014223,-0.014223
humain,0.048753,0.034532,0.014221,-0.014221
autre,0.323517,0.310964,0.012553,-0.012553
nu,0.045653,0.034293,0.011361,-0.011361
vivant,0.041520,0.031101,0.010419,-0.010419
heureux,0.075619,0.065220,0.010398,-0.010398
rouge,0.075149,0.065974,0.009175,-0.009175
bleu,0.061059,0.051950,0.009108,-0.009108
vieux,0.176319,0.167390,0.008928,-0.008928
vert,0.043023,0.034903,0.008120,-0.008120
debout,0.044432,0.036369,0.008063,-0.008063
immobile,0.033160,0.025329,0.007831,-0.007831
lointain,0.026114,0.018569,0.007545,-0.007545
froid,0.056550,0.049018,0.007531,-0.007531
rose,0.040674,0.033570,0.007105,-0.007105

In [25]:
dfLimTfidf.sort_values('lastDistinct', ascending=False).head(n=20)

,lastChaps_adj_rest,All_but_last_adj_rest,firstDistinct,lastDistinct
jeune,0.196985,0.251786,-0.054801,0.054801
bon,0.235968,0.281069,-0.045101,0.045101
joli,0.032596,0.045002,-0.012406,0.012406
cher,0.074022,0.086243,-0.012221,0.012221
large,0.033535,0.044147,-0.010612,0.010612
certain,0.044902,0.053167,-0.008265,0.008265
pauvre,0.108121,0.116244,-0.008123,0.008123
royal,0.007703,0.015204,-0.007502,0.007502
petit,0.419614,0.426557,-0.006943,0.006943
mauvais,0.053920,0.060751,-0.006832,0.006832
riche,0.026772,0.033376,-0.006604,0.006604
prisonnier,0.009582,0.015556,-0.005974,0.005974
sérieux,0.019915,0.025716,-0.005801,0.005801
naturel,0.021605,0.027304,-0.005698,0.005698
brave,0.022733,0.028383,-0.005650,0.005650
honnête,0.014654,0.020111,-0.005457,0.005457
excellent,0.011272,0.016630,-0.005357,0.005357
sûr,0.067822,0.073024,-0.005202,0.005202
charmant,0.020290,0.025451,-0.005161,0.005161
simple,0.038608,0.043384,-0.004776,0.004776